// Package config handles configuration management for Shadows.
//
// This package defines the data structures used throughout the application
// and provides functions for loading and saving configuration.
//
// In Go, a package is a collection of related .go files in the same directory.
// All files in this directory should have 'package config' at the top.
package config

import "time"

// Repository represents a work repository that has shadow file tracking enabled.
//
// In Go, a struct is a composite type that groups together fields.
// Structs are similar to classes in other languages, but simpler.
//
// Field naming convention:
// - Exported (public) fields start with uppercase: Name, WSLPath
// - Unexported (private) fields start with lowercase: id (we don't have any here)
//
// Struct tags (the backticks) provide metadata about the field.
// They're often used by packages that serialize/deserialize data.
// Format: `key:"value" key2:"value2"`
//
// Common tags:
// - json:"name" - how this field appears in JSON
// - toml:"name" - how this field appears in TOML
// - db:"name"   - database column name
// - validate:"required" - validation rules
type Repository struct {
	// ID is the unique identifier for this repository in the database.
	// It's auto-generated by SQLite (PRIMARY KEY AUTOINCREMENT).
	ID int `json:"id" toml:"id" db:"id"`

	// Name is a friendly name for the repository (usually the directory name).
	// Example: "my-work-project"
	Name string `json:"name" toml:"name" db:"name"`

	// WSLPath is the absolute path to the work repository in WSL/Linux.
	// Example: "/home/chris/work/my-project"
	WSLPath string `json:"wsl_path" toml:"wsl_path" db:"wsl_path"`

	// WindowsPath is the absolute path to the work repository in Windows.
	// Example: "C:\\Users\\chris\\work\\my-project"
	// or from WSL: "/mnt/c/Users/chris/work/my-project"
	WindowsPath string `json:"windows_path" toml:"windows_path" db:"windows_path"`

	// ShadowRepoPath is where shadow files are stored.
	// Example: "/home/chris/.shadows/repos/my-project"
	// This directory is a Git repository that mirrors the work repo structure.
	ShadowRepoPath string `json:"shadow_repo_path" toml:"shadow_repo_path" db:"shadow_repo_path"`

	// GitRemote is an optional remote URL for backing up shadow files.
	// Example: "git@github.com:chris/shadows-my-project.git"
	// Can be empty if the user doesn't want remote backup.
	GitRemote string `json:"git_remote,omitempty" toml:"git_remote,omitempty" db:"git_remote"`

	// ActiveLocation tracks where the user last worked (for conflict detection).
	// Values: "wsl", "windows", or ""
	// This helps us know which location has the most recent changes.
	ActiveLocation string `json:"active_location,omitempty" toml:"active_location,omitempty" db:"active_location"`

	// CreatedAt is when this repository was initialized in Shadows.
	// In Go, time.Time is the standard type for timestamps.
	// The database stores it as a string in ISO 8601 format.
	CreatedAt time.Time `json:"created_at" toml:"created_at" db:"created_at"`
}

// ShadowFile represents a file that's being tracked as a shadow file.
//
// Shadow files live in the work repository but are:
// - Excluded from Git (via .git/info/exclude)
// - Tracked in the shadow repository (with version history)
// - Synced between environments
type ShadowFile struct {
	// ID is the unique identifier for this shadow file in the database.
	ID int `json:"id" toml:"id" db:"id"`

	// RepositoryID links this shadow file to its repository.
	// This is a foreign key referencing Repository.ID.
	// SQL: FOREIGN KEY (repository_id) REFERENCES repositories(id)
	RepositoryID int `json:"repository_id" toml:"repository_id" db:"repository_id"`

	// RelativePath is the path to the file relative to the repository root.
	// Example: "tests/test_chris_experiment.py"
	// Example: "scripts/my_helper.sh"
	//
	// Always use forward slashes (/) even on Windows for consistency.
	// Go's filepath.Join() and filepath.ToSlash() can help with this.
	RelativePath string `json:"relative_path" toml:"relative_path" db:"relative_path"`

	// Status tracks the lifecycle of this shadow file.
	// Values:
	//   - "shadowed": actively tracked as a shadow file
	//   - "promoted": graduated to the work repository (no longer a shadow)
	//   - "deleted":  removed from shadow tracking
	Status string `json:"status" toml:"status" db:"status"`

	// AddedDate is when this file was first added to shadow tracking.
	AddedDate time.Time `json:"added_date" toml:"added_date" db:"added_date"`

	// PromotedDate is when this file was promoted to the work repository.
	// It's a pointer (*time.Time) because it can be nil (not yet promoted).
	//
	// In Go:
	// - time.Time is always a valid time (zero value is year 0001)
	// - *time.Time can be nil (no time set)
	//
	// When working with this field:
	//   if file.PromotedDate != nil {
	//       fmt.Println("Promoted on:", *file.PromotedDate)
	//   }
	PromotedDate *time.Time `json:"promoted_date,omitempty" toml:"promoted_date,omitempty" db:"promoted_date"`
}

// Config represents the global Shadows configuration.
//
// This is loaded from ~/.shadows/config.toml and contains settings
// that apply across all repositories.
type Config struct {
	// ShadowsDir is the root directory for all shadow data.
	// Default: ~/.shadows
	ShadowsDir string `json:"shadows_dir" toml:"shadows_dir"`

	// DatabasePath is the path to the SQLite database.
	// Default: ~/.shadows/shadows.db
	DatabasePath string `json:"database_path" toml:"database_path"`

	// DefaultRemoteBase is a template for generating remote URLs.
	// Example: "git@github.com:username/shadows-"
	// Then for repo "my-project", remote would be:
	//   "git@github.com:username/shadows-my-project"
	DefaultRemoteBase string `json:"default_remote_base,omitempty" toml:"default_remote_base,omitempty"`

	// AutoCommit controls whether shadow file changes are automatically committed.
	// If true, every 'shadows add' or 'shadows sync' creates a Git commit.
	// If false, user must manually commit changes in the shadow repo.
	AutoCommit bool `json:"auto_commit" toml:"auto_commit"`

	// AutoSyncOnInit controls whether 'shadows init' immediately syncs files.
	// Usually false - let the user add files first.
	AutoSyncOnInit bool `json:"auto_sync_on_init" toml:"auto_sync_on_init"`

	// Verbose controls default verbosity of output.
	// Can be overridden with --verbose flag.
	Verbose bool `json:"verbose" toml:"verbose"`
}

// Status constants for ShadowFile.Status
//
// In Go, constants are defined with 'const'. They're immutable values
// set at compile time.
//
// We group related constants in a const block.
// The 'iota' keyword can be used for auto-incrementing values,
// but here we use explicit strings for clarity.
const (
	// StatusShadowed indicates the file is actively tracked as a shadow file.
	StatusShadowed = "shadowed"

	// StatusPromoted indicates the file was promoted to the work repository.
	StatusPromoted = "promoted"

	// StatusDeleted indicates the file was removed from shadow tracking.
	StatusDeleted = "deleted"
)

// Location constants for Repository.ActiveLocation
const (
	// LocationWSL indicates the file was last modified in WSL/Linux.
	LocationWSL = "wsl"

	// LocationWindows indicates the file was last modified in Windows.
	LocationWindows = "windows"
)

// DefaultConfig returns a Config with default values.
//
// This is a common Go pattern: a function that returns a struct with
// sensible defaults. Users can then modify the returned struct as needed.
//
// Example usage:
//
//	cfg := DefaultConfig()
//	cfg.Verbose = true
func DefaultConfig() *Config {
	// In Go, we often return pointers to structs to avoid copying large objects.
	// The & operator creates a pointer to the struct.
	return &Config{
		// We'll set these properly when we implement config loading
		// For now, these are placeholders
		ShadowsDir:        "", // Will be set to ~/.shadows
		DatabasePath:      "", // Will be set to ~/.shadows/shadows.db
		DefaultRemoteBase: "",
		AutoCommit:        true,  // Default to auto-committing
		AutoSyncOnInit:    false, // Default to not auto-syncing
		Verbose:           false, // Default to non-verbose
	}
}

// IsValid checks if a Repository has all required fields.
//
// This is a method on the Repository struct.
// Methods in Go are functions with a receiver (the struct they operate on).
//
// Syntax: func (receiver Type) MethodName(params) return
//   - (r *Repository) is the receiver
//   - r is the variable name (like 'this' or 'self' in other languages)
//   - *Repository means we receive a pointer (can modify the original)
//
// We use a pointer receiver here even though we don't modify r,
// because it's more efficient (no copying) and consistent with other methods.
func (r *Repository) IsValid() bool {
	// Check that required fields are not empty
	// In Go, the zero value for strings is "" (empty string)
	return r.Name != "" &&
		r.WSLPath != "" &&
		r.ShadowRepoPath != ""
	// Note: WindowsPath is optional (user might only use WSL)
}

// IsValid checks if a ShadowFile has all required fields.
func (sf *ShadowFile) IsValid() bool {
	return sf.RepositoryID > 0 &&
		sf.RelativePath != "" &&
		sf.Status != ""
}

// IsPromoted checks if the shadow file has been promoted to the work repo.
func (sf *ShadowFile) IsPromoted() bool {
	return sf.Status == StatusPromoted && sf.PromotedDate != nil
}

// IsShadowed checks if the file is actively being tracked as a shadow file.
func (sf *ShadowFile) IsShadowed() bool {
	return sf.Status == StatusShadowed
}

// IsDeleted checks if the file has been deleted from shadow tracking.
func (sf *ShadowFile) IsDeleted() bool {
	return sf.Status == StatusDeleted
}
